version: "3.8"

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://recipe-choice-backend.onrender.com/api/v1
