version: "3.8"

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /frontend
    ports:
      - "3000:3000"
